# Generated by Django 5.0.6 on 2024-06-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_alter_appliances_price_alter_landscaping_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliances',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='landscaping',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='lighting',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='paint',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='wood',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
